// topics are from https://docs.google.com/spreadsheets/d/1A_dgJCYQsNZwxpeFDPWtdpihS0J2xvcXxhXJxZIHj10/edit#gid=0

var STORYCHECK_TOPICS = [
  {
    "icon": "fa-microphone",
    "id": "1",
    "name": "News conference",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },    
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },  
      { "key": "7" } 
    ]
  },
  {
    "icon": "fa-comment",
    "id": "2",
    "name": "Speech",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },      
      { "key": "11" }
    ]
  },
  {
    "icon": "fa-flag",
    "id": "3",
    "name": "Protest March ",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
      { "key": "14" },
      { "key": "15" },
      { "key": "16" }
    ]
  },
  {
    "icon": "fa-car",
    "id": "4",
    "name": "Motor Accidents",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
      { "key": "14" },
      { "key": "15" },
      { "key": "16" },
      { "key": "17" },
      { "key": "18" }
    ]
  },
  {
    "icon": "fa-medkit",
    "id": "5",
    "name": "Health Services",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
      { "key": "14" }
    ]
  },
  {
    "icon": "fa-gavel",
    "id": "6",
    "name": "Courts - Civil Action",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
      { "key": "14" },
    ]
  },
  {
    "icon": "fa-gavel",
    "id": "7",
    "name": "Courts - Verdict",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" }
    ]
  },
  {
    "icon": "fa-gavel",
    "id": "8",
    "name": "Crime",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" }
    ]
  },
  {
    "icon": "fa-fire",
    "id": "9",
    "name": "Fires ",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" }
    ]
  },
  {
    "icon": "fa-soccer-ball-o",
    "id": "10",
    "name": "Sports ",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
      { "key": "14" },
    ]
  },
  {
    "icon": "fa-medkit",
    "id": "11",
    "name": "Specific Illness",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" }
    ]
  },
  {
    "icon": "fa-user",
    "id": "12",
    "name": "Biography",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
    ]
  },
  {
    "icon": "fa-user",
    "id": "13",
    "name": "Obituaries",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" }
    ]
  },
  {
    "icon": "fa-university",
    "id": "14",
    "name": "Political rally",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
      { "key": "14" },
      { "key": "15" }
    ]
  },
  {
    "icon": "fa-comments",
    "id": "15",
    "name": "Election meeting",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
      { "key": "14" },
      { "key": "15" },
      { "key": "16" }
    ]
  },
  {
    "icon": "fa-calendar",
    "id": "16",
    "name": "Election day",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
    ]
  },
  {
    "icon": "fa-building",
    "id": "17",
    "name": "Incident at Public Health Facility",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
    ]
  },
  {
    "icon": "fa-venus-mars",
    "id": "18",
    "name": "Gender-based violence",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
      { "key": "13" },
    ]
  },
  {
    "icon": "fa-ambulance",
    "id": "19",
    "name": "Emergency services",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" }
    ]
  },
  {
    "icon": "fa-building",
    "id": "20",
    "name": "Health infrastructure: Building & equipment",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
    ]
  },
  {
    "icon": "fa-tint",
    "id": "21",
    "name": "Lack of Water",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
    ]
  },
  {
    "icon": "fa-tint",
    "id": "22",
    "name": "Sanitation issues",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
    ]
  },
  {
    "icon": "fa-medkit",
    "id": "23",
    "name": "Nutrition",
    "questions": [
      { "key": "1" },
      { "key": "2" },
      { "key": "3" },
      { "key": "4" },
      { "key": "5" },
      { "key": "6" },
      { "key": "7" },
      { "key": "8" },
      { "key": "9" },
      { "key": "10" },
      { "key": "11" },
      { "key": "12" },
    ]
  },
];
